#!/bin/bash

VENV="$HOME/pip-venv/bin/activate"
PROJECT_DIR="$HOME/out_parking/src"
PYTHON_PATH="$PROJECT_DIR/obstacles-challenge"
PYTHON_SCRIPT="Obstacles.py"

# Dynamically detect the USB port
UPLOAD_PORT=$(ls /dev/ttyUSB* 2>/dev/null | head -n 1)



if [ -z "$UPLOAD_PORT" ]; then
    echo "ERROR: No /dev/ttyUSB device found."
    exit 1
fi

function source_venv()
{
    source "$VENV" || { echo "Failed to activate virtualenv"; exit 1; }
}

function upload() {
    source_venv
    cd "$PROJECT_DIR" || exit 1
    platformio run -e esp32dev --target upload --upload-port "$UPLOAD_PORT" && \
    platformio device monitor --port "$UPLOAD_PORT" --baud 115200
}

function monitor() {
    source_venv
    cd "$PROJECT_DIR" || exit 1
    platformio device monitor --port "$UPLOAD_PORT" --baud 115200
}

function camera() {
    source_venv
    cd "$PYTHON_PATH" || exit 1
    python "$PYTHON_SCRIPT" --serial "$UPLOAD_PORT" "${@:2}"
}

function test_mode() {
    source_venv
    cd "$PROJECT_DIR" || exit 1
    echo "Uploading firmware in TEST MODE..."
    platformio run -e esp32dev-test --target upload --upload-port "$UPLOAD_PORT" && \
    platformio device monitor --port "$UPLOAD_PORT" --baud 115200
}
case "$1" in
    upload)
        upload
        ;;
    monitor)
        monitor
        ;;
    camera)
        camera "$@"
        ;;
    test)
        test_mode
        ;;
    *)
        echo "Usage: $0 {camera|upload|monitor|test} [args...]"
        exit 1
        ;;
esac

